//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Town_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli_knjizeno
    {
        public int sifra { get; set; }
        public string grupa { get; set; }
        public string artikal { get; set; }
        public int kolicina { get; set; }
        public decimal nabavna_cena { get; set; }
        public decimal prodajna_cena { get; set; }
    }
}
